### ISSUE TITLE
Upload lên hosting

### ISSUE THREAD

**Issue by VyKhoaKFC** [leephan2k1/manga-app#2]
Dạ cho em hỏi về phần up lên hosting ạ, sau khi up lên thì em sẽ cần phải thiết lập các file như thế nào vậy ạ và file trang chủ là index.tsx phải không ạ ?

Mong anh giúp đáp giúp em

**Comment by leephan2k1** [comment]
Hiện tại mình dùng VPS với cấu hình Ngix để self host server (https://github.com/leephan2k1/manga-scraper/tree/disable-redis/src) còn client (NextJS) thì mình dùng netlify nha.
Bạn không có VPS thì mình thấy dùng https://railway.app hosting cũng được (Hoặc sửa code lại để chạy 100% trên server NextJS trên Netlify luôn cũng được, nhưng chạy code server nhiều quá thì bị charge phí ấy) 

Bên Netlify bạn vô  app.netlify.com rồi cấu hình env như mình viết (Phải đi đăng ký khá nhiều cái để lấy key ấy: https://github.com/leephan2k1/manga-app#project-setup

Do mình viết lại code cho database rồi nên setup theo hướng dẫn không đúng nữa nên bạn merge nhánh kyoto-manga-v1 vào main để up.

**Comment by leephan2k1** [comment]
Mình mới viết hướng dẫn cài đặt cở sở dữ liệu: Bạn tham khảo và kết nối https://github.com/leephan2k1/manga-app/blob/main/Database.Vi.md#hosting
