### ISSUE TITLE
[Bug] Can't read manga from Otakusan Source

### ISSUE THREAD

**Issue by nayumiDEV** [leephan2k1/manga-app#4]
Proof: [Click](https://kyotomanga.live/manga/read/NTC/1/chapter/2334/that-nghiep-chuyen-sinh-lam-lai-het-suc-chap-1)

**Comment by leephan2k1** [comment]
Maybe the page data was confused.
I fixed it.
You can visit again: [chapter-1](https://kyotomanga.live/manga/read/NTC/1/truyen-tranh/that-nghiep-chuyen-sinh-lam-lai-het-suc/chap-1/95355)
or navigate to the details page : [details page](https://kyotomanga.live/manga/details/that-nghiep-chuyen-sinh-lam-lai-het-suc-46601)
